name: My First Worflow

on:
  # ทำงาน ตอนไหน push ลง main
  push:
    branches:
      - main

# jobs อะไร
jobs:
  build: #ชื่อ job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository # เป็นดึง code มาไว้ใน runner เพื่อให้ job อื่นเข้าถึงไฟล์ได้
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, Github Actions!"
